### ISSUE TITLE
feat/newpassword

### ISSUE THREAD

**Issue by MarinaKrasnov** [staff-motivation/Motivation_Personal#11]
stack: react-hook-form , yup

![Image](https://github.com/staff-motivation/Motivation_Personal/assets/93862896/b1f7cd08-bd30-4488-bf9b-191fd8b3d268)

**Comment by MarinaKrasnov** [comment]
1.3 из дизайн макета

**Comment by Anterul** [comment]
Марина, кажется мы перепутали задачи сброс это - 1.3, новый 1.5 ?

**Comment by MarinaKrasnov** [comment]
да, ты прав.
Егор делай 1.5 из дизайн макета.
