### ISSUE TITLE
New component ResetPassword

### ISSUE THREAD

**Issue by MarinaKrasnov** [staff-motivation/Motivation_Personal#25]
![Image](https://github.com/staff-motivation/Motivation_Personal/assets/93862896/3350757d-0ad8-4055-a356-3866773aacd3)

**Comment by Anterul** [comment]
разве 1.3 это не сброс, а 1.5 это новый ?

**Comment by MarinaKrasnov** [comment]
сделай тогда еще то что надо было сделать

вт, 15 авг. 2023 г. в 22:36, Андрей ***@***.***>:

**Comment by Anterul** [comment]
без проблем, но 1.5 разве не делает Егор ?

**Comment by MarinaKrasnov** [comment]
отбой, пусть егор сделает
