### ISSUE TITLE
Frontend: Провести оценку часах задачи разработки фич 1.1; 1.2; 1.3 и внести данные в таблицу. В этой же таблице в столбце "Вопросы к обсуждению" внести свои комментарии по фичам.

### ISSUE THREAD

**Issue by ElenaTatsiy** [staff-motivation/Motivation_Personal#7]

**Comment by MarinaKrasnov** [comment]
По 8 часов поставила на каждую задачу. И максимум 24. И мы пока не видели дизайн макет и как будет организован процесс ревью, ,будет ли готов бек для тестов, много неизвестных переменных. Часы очень предварительные при условии что бек уже готов для тестов.
